# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yamux < Formula
  desc "Multiplexer"
  homepage "https://github.com/nwtgck/yamux-cli"
  version "0.1.0-release-trigger1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/yamux-cli/releases/download/v0.1.0-release-trigger1/yamux-0.1.0-release-trigger1-darwin-amd64.tar.gz"
    sha256 "18df0e8e5e1fe9567eb37e9a6306b1b4681af7b3582af039e886d5441c43c8be"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/nwtgck/yamux-cli/releases/download/v0.1.0-release-trigger1/yamux-0.1.0-release-trigger1-darwin-arm64.tar.gz"
    sha256 "a1e6d684dbf59333dec09035cac5f689faeace706ba7c296ce586b553a97c5a1"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/yamux-cli/releases/download/v0.1.0-release-trigger1/yamux-0.1.0-release-trigger1-linux-amd64.tar.gz"
    sha256 "9453f053b2c19f8bd3847735f20a34f6fa11475342af3a0b766222e279941440"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/yamux-cli/releases/download/v0.1.0-release-trigger1/yamux-0.1.0-release-trigger1-linux-armv6.tar.gz"
    sha256 "eda7aa84f94fe7aa737ef9ff757f29d6afd66121e5cbf53a4adc237602a8ee38"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/yamux-cli/releases/download/v0.1.0-release-trigger1/yamux-0.1.0-release-trigger1-linux-arm64.tar.gz"
    sha256 "da987c4f01f3c205faa32626073f82fd969d5f81fed6b928b9869159ff19babe"
  end

  def install
    bin.install "yamux"
  end
end
